/* -*- mode: c++ -*-
 * Kaleidoscope-host_keymap -- A utility for the generation 
 *                          of Kaleidoscope host_keymap files 
 * Copyright (C) 2019 noseglasses (shinynoseglasses@gmail.com)
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
#pragma once

#define KALEIDOSCOPE_HID_KEYS(OP) \
   OP(HID_KEYBOARD_NO_EVENT, Key_NoEvent) \
   OP(HID_KEYBOARD_ERROR_ROLLOVER, Key_ErrorRollover) \
   OP(HID_KEYBOARD_POST_FAIL, Key_PostFail) \
   OP(HID_KEYBOARD_ERROR_UNDEFINED, Key_ErrorUndefined) \
   OP(HID_KEYBOARD_A_AND_A, Key_A) \
   OP(HID_KEYBOARD_B_AND_B, Key_B) \
   OP(HID_KEYBOARD_C_AND_C, Key_C) \
   OP(HID_KEYBOARD_D_AND_D, Key_D) \
   OP(HID_KEYBOARD_E_AND_E, Key_E) \
   OP(HID_KEYBOARD_F_AND_F, Key_F) \
   OP(HID_KEYBOARD_G_AND_G, Key_G) \
   OP(HID_KEYBOARD_H_AND_H, Key_H) \
   OP(HID_KEYBOARD_I_AND_I, Key_I) \
   OP(HID_KEYBOARD_J_AND_J, Key_J) \
   OP(HID_KEYBOARD_K_AND_K, Key_K) \
   OP(HID_KEYBOARD_L_AND_L, Key_L) \
   OP(HID_KEYBOARD_M_AND_M, Key_M) \
   OP(HID_KEYBOARD_N_AND_N, Key_N) \
   OP(HID_KEYBOARD_O_AND_O, Key_O) \
   OP(HID_KEYBOARD_P_AND_P, Key_P) \
   OP(HID_KEYBOARD_Q_AND_Q, Key_Q) \
   OP(HID_KEYBOARD_R_AND_R, Key_R) \
   OP(HID_KEYBOARD_S_AND_S, Key_S) \
   OP(HID_KEYBOARD_T_AND_T, Key_T) \
   OP(HID_KEYBOARD_U_AND_U, Key_U) \
   OP(HID_KEYBOARD_V_AND_V, Key_V) \
   OP(HID_KEYBOARD_W_AND_W, Key_W) \
   OP(HID_KEYBOARD_X_AND_X, Key_X) \
   OP(HID_KEYBOARD_Y_AND_Y, Key_Y) \
   OP(HID_KEYBOARD_Z_AND_Z, Key_Z) \
   OP(HID_KEYBOARD_1_AND_EXCLAMATION_POINT, Key_1) \
   OP(HID_KEYBOARD_2_AND_AT, Key_2) \
   OP(HID_KEYBOARD_3_AND_POUND, Key_3) \
   OP(HID_KEYBOARD_4_AND_DOLLAR, Key_4) \
   OP(HID_KEYBOARD_5_AND_PERCENT, Key_5) \
   OP(HID_KEYBOARD_6_AND_CARAT, Key_6) \
   OP(HID_KEYBOARD_7_AND_AMPERSAND, Key_7) \
   OP(HID_KEYBOARD_8_AND_ASTERISK, Key_8) \
   OP(HID_KEYBOARD_9_AND_LEFT_PAREN, Key_9) \
   OP(HID_KEYBOARD_0_AND_RIGHT_PAREN, Key_0) \
   OP(HID_KEYBOARD_ENTER, Key_Enter) \
   OP(HID_KEYBOARD_ESCAPE, Key_Escape) \
   OP(HID_KEYBOARD_DELETE, Key_Backspace) \
   OP(HID_KEYBOARD_TAB, Key_Tab) \
   OP(HID_KEYBOARD_SPACEBAR, Key_Spacebar) \
   OP(HID_KEYBOARD_MINUS_AND_UNDERSCORE, Key_Minus) \
   OP(HID_KEYBOARD_EQUALS_AND_PLUS, Key_Equals) \
   OP(HID_KEYBOARD_LEFT_BRACKET_AND_LEFT_CURLY_BRACE, Key_LeftBracket) \
   OP(HID_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_CURLY_BRACE, Key_RightBracket) \
   OP(HID_KEYBOARD_BACKSLASH_AND_PIPE, Key_Backslash) \
   OP(HID_KEYBOARD_NON_US_POUND_AND_TILDE, Key_NonUsPound) \
   OP(HID_KEYBOARD_SEMICOLON_AND_COLON, Key_Semicolon) \
   OP(HID_KEYBOARD_QUOTE_AND_DOUBLEQUOTE, Key_Quote) \
   OP(HID_KEYBOARD_GRAVE_ACCENT_AND_TILDE, Key_Backtick) \
   OP(HID_KEYBOARD_COMMA_AND_LESS_THAN, Key_Comma) \
   OP(HID_KEYBOARD_PERIOD_AND_GREATER_THAN, Key_Period) \
   OP(HID_KEYBOARD_SLASH_AND_QUESTION_MARK, Key_Slash) \
   OP(HID_KEYBOARD_CAPS_LOCK, Key_CapsLock) \
   OP(HID_KEYBOARD_F1, Key_F1) \
   OP(HID_KEYBOARD_F2, Key_F2) \
   OP(HID_KEYBOARD_F3, Key_F3) \
   OP(HID_KEYBOARD_F4, Key_F4) \
   OP(HID_KEYBOARD_F5, Key_F5) \
   OP(HID_KEYBOARD_F6, Key_F6) \
   OP(HID_KEYBOARD_F7, Key_F7) \
   OP(HID_KEYBOARD_F8, Key_F8) \
   OP(HID_KEYBOARD_F9, Key_F9) \
   OP(HID_KEYBOARD_F10, Key_F10) \
   OP(HID_KEYBOARD_F11, Key_F11) \
   OP(HID_KEYBOARD_F12, Key_F12) \
   OP(HID_KEYBOARD_PRINTSCREEN, Key_PrintScreen) \
   OP(HID_KEYBOARD_SCROLL_LOCK, Key_ScrollLock) \
   OP(HID_KEYBOARD_PAUSE, Key_Pause) \
   OP(HID_KEYBOARD_INSERT, Key_Insert) \
   OP(HID_KEYBOARD_HOME, Key_Home) \
   OP(HID_KEYBOARD_PAGE_UP, Key_PageUp) \
   OP(HID_KEYBOARD_DELETE_FORWARD, Key_Delete) \
   OP(HID_KEYBOARD_END, Key_End) \
   OP(HID_KEYBOARD_PAGE_DOWN, Key_PageDown) \
   OP(HID_KEYBOARD_RIGHT_ARROW, Key_RightArrow) \
   OP(HID_KEYBOARD_LEFT_ARROW, Key_LeftArrow) \
   OP(HID_KEYBOARD_DOWN_ARROW, Key_DownArrow) \
   OP(HID_KEYBOARD_UP_ARROW, Key_UpArrow) \
   OP(HID_KEYPAD_NUM_LOCK_AND_CLEAR, Key_KeypadNumLock) \
   OP(HID_KEYPAD_DIVIDE, Key_KeypadDivide) \
   OP(HID_KEYPAD_MULTIPLY, Key_KeypadMultiply) \
   OP(HID_KEYPAD_SUBTRACT, Key_KeypadSubtract) \
   OP(HID_KEYPAD_ADD, Key_KeypadAdd) \
   OP(HID_KEYPAD_ENTER, Key_KeypadEnter) \
   OP(HID_KEYPAD_1_AND_END, Key_Keypad1) \
   OP(HID_KEYPAD_2_AND_DOWN_ARROW, Key_Keypad2) \
   OP(HID_KEYPAD_3_AND_PAGE_DOWN, Key_Keypad3) \
   OP(HID_KEYPAD_4_AND_LEFT_ARROW, Key_Keypad4) \
   OP(HID_KEYPAD_5, Key_Keypad5) \
   OP(HID_KEYPAD_6_AND_RIGHT_ARROW, Key_Keypad6) \
   OP(HID_KEYPAD_7_AND_HOME, Key_Keypad7) \
   OP(HID_KEYPAD_8_AND_UP_ARROW, Key_Keypad8) \
   OP(HID_KEYPAD_9_AND_PAGE_UP, Key_Keypad9) \
   OP(HID_KEYPAD_0_AND_INSERT, Key_Keypad0) \
   OP(HID_KEYPAD_PERIOD_AND_DELETE, Key_KeypadDot) \
   OP(HID_KEYBOARD_NON_US_BACKSLASH_AND_PIPE, Key_NonUsBackslashAndPipe) \
   OP(HID_KEYBOARD_APPLICATION, Key_PcApplication) \
   OP(HID_KEYBOARD_POWER, Key_Power) \
   OP(HID_KEYPAD_EQUALS, Key_KeypadEquals) \
   OP(HID_KEYBOARD_F13, Key_F13) \
   OP(HID_KEYBOARD_F14, Key_F14) \
   OP(HID_KEYBOARD_F15, Key_F15) \
   OP(HID_KEYBOARD_F16, Key_F16) \
   OP(HID_KEYBOARD_F17, Key_F17) \
   OP(HID_KEYBOARD_F18, Key_F18) \
   OP(HID_KEYBOARD_F19, Key_F19) \
   OP(HID_KEYBOARD_F20, Key_F20) \
   OP(HID_KEYBOARD_F21, Key_F21) \
   OP(HID_KEYBOARD_F22, Key_F22) \
   OP(HID_KEYBOARD_F23, Key_F23) \
   OP(HID_KEYBOARD_F24, Key_F24) \
   OP(HID_KEYBOARD_EXECUTE, Key_Execute) \
   OP(HID_KEYBOARD_HELP, Key_Help) \
   OP(HID_KEYBOARD_MENU, Key_Menu) \
   OP(HID_KEYBOARD_SELECT, Key_Select) \
   OP(HID_KEYBOARD_STOP, Key_Stop) \
   OP(HID_KEYBOARD_AGAIN, Key_Again) \
   OP(HID_KEYBOARD_UNDO, Key_Undo) \
   OP(HID_KEYBOARD_CUT, Key_Cut) \
   OP(HID_KEYBOARD_COPY, Key_Copy) \
   OP(HID_KEYBOARD_PASTE, Key_Paste) \
   OP(HID_KEYBOARD_FIND, Key_Find) \
   OP(HID_KEYBOARD_MUTE, Key_Mute) \
   OP(HID_KEYBOARD_VOLUME_UP, Key_VolumeUp) \
   OP(HID_KEYBOARD_VOLUME_DOWN, Key_VolumeDown) \
   OP(HID_KEYBOARD_LOCKING_CAPS_LOCK, Key_LockingCapsLock) \
   OP(HID_KEYBOARD_LOCKING_NUM_LOCK, Key_LockingNumLock) \
   OP(HID_KEYBOARD_LOCKING_SCROLL_LOCK, Key_LockingScrollLock) \
   OP(HID_KEYPAD_COMMA, Key_KeypadComma) \
   OP(HID_KEYPAD_EQUAL_SIGN, Key_KeypadEqualSign) \
   OP(HID_KEYBOARD_INTERNATIONAL1, Key_International1) \
   OP(HID_KEYBOARD_INTERNATIONAL2, Key_International2) \
   OP(HID_KEYBOARD_INTERNATIONAL3, Key_International3) \
   OP(HID_KEYBOARD_INTERNATIONAL4, Key_International4) \
   OP(HID_KEYBOARD_INTERNATIONAL5, Key_International5) \
   OP(HID_KEYBOARD_INTERNATIONAL6, Key_International6) \
   OP(HID_KEYBOARD_INTERNATIONAL7, Key_International7) \
   OP(HID_KEYBOARD_INTERNATIONAL8, Key_International8) \
   OP(HID_KEYBOARD_INTERNATIONAL9, Key_International9) \
   OP(HID_KEYBOARD_LANG1, Key_Lang1) \
   OP(HID_KEYBOARD_LANG2, Key_Lang2) \
   OP(HID_KEYBOARD_LANG3, Key_Lang3) \
   OP(HID_KEYBOARD_LANG4, Key_Lang4) \
   OP(HID_KEYBOARD_LANG5, Key_Lang5) \
   OP(HID_KEYBOARD_LANG6, Key_Lang6) \
   OP(HID_KEYBOARD_LANG7, Key_Lang7) \
   OP(HID_KEYBOARD_LANG8, Key_Lang8) \
   OP(HID_KEYBOARD_LANG9, Key_Lang9) \
   OP(HID_KEYBOARD_ALTERNATE_ERASE, Key_AlternateErase) \
   OP(HID_KEYBOARD_SYSREQ_SLASH_ATTENTION, Key_Sysreq) \
   OP(HID_KEYBOARD_CANCEL, Key_Cancel) \
   OP(HID_KEYBOARD_CLEAR, Key_Clear) \
   OP(HID_KEYBOARD_PRIOR, Key_Prior) \
   OP(HID_KEYBOARD_RETURN, Key_Return) \
   OP(HID_KEYBOARD_SEPARATOR, Key_Separator) \
   OP(HID_KEYBOARD_OUT, Key_Out) \
   OP(HID_KEYBOARD_OPER, Key_Oper) \
   OP(HID_KEYBOARD_CLEAR_SLASH_AGAIN, Key_ClearSlashAgain) \
   OP(HID_KEYBOARD_CRSEL_SLASH_PROPS, Key_CrselSlashProps) \
   OP(HID_KEYBOARD_EXSEL, Key_Exsel) \
   OP(HID_KEYPAD_00, Key_Keypad00) \
   OP(HID_KEYPAD_000, Key_Keypad000) \
   OP(HID_THOUSANDS_SEPARATOR, Key_ThousandsSeparator) \
   OP(HID_DECIMAL_SEPARATOR, Key_DecimalSeparator) \
   OP(HID_CURRENCY_UNIT, Key_CurrencyUnit) \
   OP(HID_CURRENCY_SUBUNIT, Key_CurrencySubunit) \
   OP(HID_KEYPAD_LEFT_PAREN, Key_KeypadLeftParen) \
   OP(HID_KEYPAD_RIGHT_PAREN, Key_KeypadRightParen) \
   OP(HID_KEYPAD_LEFT_CURLY_BRACE, Key_KeypadLeftCurlyBrace) \
   OP(HID_KEYPAD_RIGHT_CURLY_BRACE, Key_KeypadRightCurlyBrace) \
   OP(HID_KEYPAD_TAB, Key_KeypadTab) \
   OP(HID_KEYPAD_BACKSPACE, Key_KeypadBackspace) \
   OP(HID_KEYPAD_A, Key_KeypadA) \
   OP(HID_KEYPAD_B, Key_KeypadB) \
   OP(HID_KEYPAD_C, Key_KeypadC) \
   OP(HID_KEYPAD_D, Key_KeypadD) \
   OP(HID_KEYPAD_E, Key_KeypadE) \
   OP(HID_KEYPAD_F, Key_KeypadF) \
   OP(HID_KEYPAD_XOR, Key_KeypadXor) \
   OP(HID_KEYPAD_CARAT, Key_KeypadCarat) \
   OP(HID_KEYPAD_PERCENT, Key_KeypadPercent) \
   OP(HID_KEYPAD_LESS_THAN, Key_KeypadLessThan) \
   OP(HID_KEYPAD_GREATER_THAN, Key_KeypadGreaterThan) \
   OP(HID_KEYPAD_AMPERSAND, Key_KeypadAmpersand) \
   OP(HID_KEYPAD_DOUBLEAMPERSAND, Key_KeypadDoubleampersand) \
   OP(HID_KEYPAD_PIPE, Key_KeypadPipe) \
   OP(HID_KEYPAD_DOUBLEPIPE, Key_KeypadDoublepipe) \
   OP(HID_KEYPAD_COLON, Key_KeypadColon) \
   OP(HID_KEYPAD_POUND_SIGN, Key_KeypadPoundSign) \
   OP(HID_KEYPAD_SPACE, Key_KeypadSpace) \
   OP(HID_KEYPAD_AT_SIGN, Key_KeypadAtSign) \
   OP(HID_KEYPAD_EXCLAMATION_POINT, Key_KeypadExclamationPoint) \
   OP(HID_KEYPAD_MEMORY_STORE, Key_KeypadMemoryStore) \
   OP(HID_KEYPAD_MEMORY_RECALL, Key_KeypadMemoryRecall) \
   OP(HID_KEYPAD_MEMORY_CLEAR, Key_KeypadMemoryClear) \
   OP(HID_KEYPAD_MEMORY_ADD, Key_KeypadMemoryAdd) \
   OP(HID_KEYPAD_MEMORY_SUBTRACT, Key_KeypadMemorySubtract) \
   OP(HID_KEYPAD_MEMORY_MULTIPLY, Key_KeypadMemoryMultiply) \
   OP(HID_KEYPAD_MEMORY_DIVIDE, Key_KeypadMemoryDivide) \
   OP(HID_KEYPAD_PLUS_SLASH_MINUS, Key_KeypadPlusSlashMinus) \
   OP(HID_KEYPAD_CLEAR, Key_KeypadClear) \
   OP(HID_KEYPAD_CLEAR_ENTRY, Key_KeypadClearEntry) \
   OP(HID_KEYPAD_BINARY, Key_KeypadBinary) \
   OP(HID_KEYPAD_OCTAL, Key_KeypadOctal) \
   OP(HID_KEYPAD_DECIMAL, Key_KeypadDecimal) \
   OP(HID_KEYPAD_HEXADECIMAL, Key_KeypadHexadecimal) \
   OP(HID_KEYBOARD_LEFT_CONTROL, Key_LeftControl) \
   OP(HID_KEYBOARD_LEFT_SHIFT, Key_LeftShift) \
   OP(HID_KEYBOARD_LEFT_ALT, Key_LeftAlt) \
   OP(HID_KEYBOARD_LEFT_GUI, Key_LeftGui) \
   OP(HID_KEYBOARD_RIGHT_CONTROL, Key_RightControl) \
   OP(HID_KEYBOARD_RIGHT_SHIFT, Key_RightShift) \
   OP(HID_KEYBOARD_RIGHT_ALT, Key_RightAlt) \
   OP(HID_KEYBOARD_RIGHT_GUI, Key_RightGui)
